### PR TITLE
Fixed typos, prettified output

### PR DESCRIPTION
**Pull request by zurawiki**
- Fixed some mis-spellings
- Changed output text for consistency
- if no args are given, do not print command undefined not found

I also reformatted to code for consistency.

I tested this on my systems but please test this patch before accepting it.

I also sent a pull request to nodeamir: (The error was just for testing purposes. The bug in that pull request is not in this patch.)
https://github.com/arunoda/nodemiral/pull/9

If they accept it, mup should look a lot nicer!

### CODE REVIEW

**Comment by arunoda** [comment]
Thanks for the update. I really like to accept this.
But you've used 4 spaces for the indentation, but Meteor UP only uses 2 spaces. If you change that, I'm super excited to take this in.

**Comment by zurawiki** [comment]
I'll send you the update soon. 

By the way, what is the proper title for mup?

Meteor-UP?
MeteorUp?
Meteor UP?

**Comment by arunoda** [comment]
Thanks.

That's a interesting question. I am also not quite sure about that. But I
like Meteor Up term.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by cristiandley** [comment]
MrUP

2014-05-07 13:03 GMT-03:00 Roger Zurawicki notifications@github.com:

> I'll send you the update soon.
> 
> By the way, what is the proper title for mup?
> 
> Meteor-UP?
> MeteorUp?
> Meteor UP?
> 
> > On May 7, 2014, at 11:56 AM, Arunoda Susiripala <

**Comment by zurawiki** [comment]
I'll make a new pull request

**Pull request closed without merging**
