### PR TITLE
Deploying multiple apps to one server

### PR DESCRIPTION
**Pull request by yasinuslu**
I'm managing multiple meteor apps in one server with nginx. This includes:
- Deploying multiple apps to one server
- Using custom `meteor` ( possibly from a checkout )
- An upstart script named `meteor-all` that can start/stop all apps.
- instance feature for `meteor` upstart script

### CODE REVIEW

**Comment by yasinuslu** [comment]
I wanted to target this PR to a new dev branch but github didn't allow it.

**Comment by arunoda** [comment]
Wow. This is a huge PR. I might need some time read this carefully. But I'm very interested. I just wanna make sure API is backward compatible.

Hopefully I can work on this tomorrow.

**Comment by yasinuslu** [comment]
Thanks for quick reply. There isn't much change in the API but there are following changes on usage:
- starting and stopping jobs `start meteor APP=<app-name>`
- app key in mup.json changed

```
"app": {
    "local": "/path/to/app",
    "name": "app-name-on-remote"
}
```

**Comment by arunoda** [comment]
I'll move into a new branch. I normally don't merge from the UI. So it is okay.

**Comment by arunoda** [comment]
Yes. But all previous mup.json files needs to be compatible with the API. So nothing breaks. BTW: Is there any option to specify the port?

**Comment by yasinuslu** [comment]
Well currently there isn't anything related to nginx and "env.PORT" does the job, all options related to hosting is up to user :)

**Comment by arunoda** [comment]
okay.

On Sun, Jan 26, 2014 at 12:00 AM, Yasin Uslu notifications@github.comwrote:

> Well currently there isn't anything related to nginx and "env.PORT" does
> the job, all options related to hosting is up to user :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/pull/20#issuecomment-33296002
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by yasinuslu** [comment]
I'll be glad to work on an `nginx` feature in the future. I just needed to do this quickly. Hopefully i'll have some time next month.

**Comment by arunoda** [comment]
Okay. cool. We can some plugin layer or something. I'll look into this more.

On Sun, Jan 26, 2014 at 12:04 AM, Yasin Uslu notifications@github.comwrote:

> I'll be glad to work on an nginx feature in the future. I just needed to
> do this quickly. Hopefully i'll have some time next month.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/pull/20#issuecomment-33296107
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
I forgot to say thank you :)

On Sun, Jan 26, 2014 at 12:04 AM, Arunoda Susiripala <
arunoda.susiripala@gmail.com> wrote:

> Okay. cool. We can some plugin layer or something. I'll look into this
> more.
> 
> On Sun, Jan 26, 2014 at 12:04 AM, Yasin Uslu notifications@github.comwrote:
> 
> > I'll be glad to work on an nginx feature in the future. I just needed to
> > do this quickly. Hopefully i'll have some time next month.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/pull/20#issuecomment-33296107
> > .
> 
> ## 
> 
> Arunoda Susiripala
> 
> @arunoda http://twitter.com/arunoda
> http://gplus.to/arunodahttps://github.com/arunoda
> http://www.linkedin.com/in/arunoda

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by yasinuslu** [comment]
Thank you for starting this project.

**Comment by yasinuslu** [comment]
I just realized big problems with the upstart jobs. It was working when i tested before now it seems that `meteor-all` job can't start other jobs, i don't know much about upstart and i'm not a bash expert :) can you look into this too ?

**Comment by arunoda** [comment]
Sure. I'll do this.

On Sun, Jan 26, 2014 at 12:52 AM, Yasin Uslu notifications@github.comwrote:

> I just realized big problems with the upstart jobs. It was working when i
> tested before now it seems that meteor-all job can't start other jobs, i
> don't know much about upstart and i'm not a bash expert :) can you look
> into this too ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/pull/20#issuecomment-33297406
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by thinkinsysdev** [comment]
Looking forward to this feature - Multiple apps on the same server!, Also how do we change a deployed app (App 1 is deployed to change the deploy to App 2 )

**Comment by arunoda** [comment]
This is much complex than it seems, if we need a generalized solution. So I
need some more time. My current focus on Meteor Up is to support Solaris as
a deployment server.

Which helps us do debug Meteor in production is style with some of the
NodeJS debugging tools.

On Tue, Jan 28, 2014 at 6:22 AM, tanmay80 notifications@github.com wrote:

> Looking forward to this feature - Multiple apps on the same server!, Also
> how do we change a deployed app (App 1 is deployed to change the deploy to
> App 2 )
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/pull/20#issuecomment-33441045
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by manuel-schoebel** [comment]
I would love this one too :)

**Comment by arunoda** [comment]
see #40 and it has been merged.

**Pull request closed without merging**
