### PR TITLE
improved readme

### PR DESCRIPTION
**Pull request by SachaG**

### CODE REVIEW

**Comment by SachaG** [comment]
I improved the readme a bit, but you should double-check the part about multiple deployment targets to make sure what I'm saying is right :)

**Comment by arunoda** [comment]
Awesome. I never expect it much sooner :)

I did some minor tweaks(8460112cb39c3a154ff74506f8125ea26c371d43) to give some better meaning. Hope you are okay with it.

**Comment by SachaG** [comment]
Cool :)

**Comment by arunoda** [comment]
Nice.

**Pull request merged**
