### PR TITLE
Made nodejs and phantomjs installation optional

### PR DESCRIPTION
**Pull request by mugli**
I have made nodejs and phantomjs installation optional in meteor-up. This pull request follows issue: https://github.com/arunoda/meteor-up/issues/22

### CODE REVIEW

**Comment by arunoda** [comment]
Thanks. 

I prefer to use the term setupMongo and setupPhantom.
By default this will be true. You can add it the config.js by checking these fields for undefined.

**Comment by mugli** [comment]
You meant setupNode and setupPhantom? Okay. I'll make the changes and send another PR.

**Comment by arunoda** [comment]
Yes. Don't send another PR. Just add a new commit. GitHub can detect it :)

On Friday, January 31, 2014, Mehdi Hasan Khan notifications@github.com
wrote:

> You meant setupNode and setupPhantom? Okay. I'll make the changes and send
> another PR.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/pull/23#issuecomment-33748159
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by mugli** [comment]
Is it ok now?

**Comment by arunoda** [comment]
Excellent.  I will do a release today.

**Comment by arunoda** [comment]
released with version: 0.1.11

**Pull request merged**
