### PR TITLE
Let's Encrypt integration

### PR DESCRIPTION
**Pull request by carlosbaraza**
Hi @arunoda,

This PR is dependent of the PR meteorhacks/mup-frontend-server#10, which integrates the TLS certificate generation in the Docker image.

If you have any questions or suggestions to improve this, I will be happy to discuss it.

### CODE REVIEW

**Comment by carlosbaraza** [comment]
Unfortunately, a commit I did to fix something else got in my branch by mistake. If you wish to merge them separately, let me know and I fix the issue creating a new branch.

**Comment by carlosbaraza** [comment]
A possible improvement would be to implement some way to verify if the certificate was created correctly and give a feedback to the user when running the `deploy` command.

**Comment by carlosbaraza** [comment]
Right now, the CLI finishes and behind the scenes, the container is trying to generate the certificate. This process takes a while and the user has no feedback to know when it is ready or if something went wrong.

A way to reproduce this bad user experience is to add a wrong domain in `tlsDomains`. This will end up with the container restarting infinitely. Therefore, a way to verify the creation of the certificate is needed before exiting the CLI.

Right now I have no more time to work on it but I will try to finish it soon. If someone wants to contribute to it, feel free.

**Comment by MasterJames** [comment]
You should take this to the new port over at kadirahq no PRs have been merged here in a long time and I fear they won't ever. There it is more like the development branch here called mupx, so hopefully you worked on that branch.

**Comment by carlosbaraza** [comment]
Hi @MasterJames,

Thanks for the notice.

However, it is awkward that there is no deprecation note or anything. I just learned that there is another repo. Wasn't it possible to transfer this repo instead of creating a new repo with all the confusion it brings?

I will try to adapt this development to the new repo though as soon as I have some time.

**Comment by MasterJames** [comment]
It's appreciated and an unofficial apology I offer. I'm sure there will be a note redirecting people there in another month or so when it's finished and ready. I'll also wager to say: The device branch mupx, never replaced mup because it was different enough that people needed mup still and so it will stay on for those that need it, while the superior docker centric mupx (as it solves many problems people had with mup) , will join the wonders of the more marketable kadirahq suite.
When to integrate new ideas?  Sooner then later is a safer bet.

**Comment by carlosbaraza** [comment]
@MasterJames thanks again. I actually like the Docker centric approach and the new repo is much more elegant in terms of code and architecture. I look forward to implementing this feature in that repo.

**Comment by carlosbaraza** [comment]
For anyone interested, I opened a ticket to track the integration in the new version of Meteor Up: kadirahq/meteor-up#54

This PR will be therefore closed, as this will never be merged to mupx.

**Pull request closed without merging**
