### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by javdl**
Took me a long long time to figure this out. Might help others making spiderable work

### CODE REVIEW

**Comment by arunoda** [comment]
Thanks. Does https is required?

**Comment by javdl** [comment]
Yes, for SSL + spiderable it is. (When you have FORCED SSL in cloudflare, https only sites) For just Meteor on SSL it is not necessarily needed.

**Comment by arunoda** [comment]
Could you include that as well. Otherwise, someone might think SSL support is must to use spiderable.

**Comment by javdl** [comment]
@arunoda done!

**Comment by Joostvanderlaan** [comment]
@arunoda Done!

**Comment by arunoda** [comment]
Awesome. 
BTW: Now mup has SSL support too. I'm testing it right now. Will add the docs :)

**Comment by arunoda** [comment]
Here's the SSL support docs: https://github.com/arunoda/meteor-up#ssl-support

**Comment by javdl** [comment]
Nice! But Node.js is not that good at serving http / https request right (static files mainly). That's why it is recommended to use a proxy like NGINX / Haproxy for static files when using Node.
If I'm gonna use it: will it also work with Meteor Cluster?

**Comment by arunoda** [comment]
If you are using, Nginx as a static file server. Yes Cluster will still work.
Cluster works on the application layer. So, it's fine.

**Pull request merged**
