### PR TITLE
Add Custom mongod.conf support

### PR DESCRIPTION
**Pull request by yasinuslu**
- I realized that upstart job for mongodb was using `/etc/mongod.conf` instead of `/etc/mongodb.conf` so the file we were sending to the server wasn't being used.
- I renamed `mongodb.conf` to `mongod.conf` (it seemed logical because server is using `/etc/mongod.conf`)
- I added a custom `mongod.conf` support. If you have a `mongod.conf` file in the deploy project folder mongodb will be restarted with that config file when you use `mup reconfig`. This mongod.conf file will be used also with `mup setup`.
- I was getting `build is not a command` error when i try `mup deploy` i changed it to use `meteor bundle` command.

EDIT: i forgot to mention it, i was configured my sublime to beautify on save, i accidentally messed with the code style. Sorry about that :)

### CODE REVIEW

**Comment by foobarbecue** [comment]
I had the "build is not a command" problem too! Please merge this PR.

**Comment by arunoda** [comment]
@foobarbecue That's the since you are using a older version of Meteor. so use mup version 0.6.5 until you update meteor.

see more: https://github.com/arunoda/meteor-up/issues/143#issuecomment-58612916

**Comment by yasinuslu** [comment]
It sucks to be stuck with an old version, i'm gonna quietly close the PR then :)

**Comment by arunoda** [comment]
I know it's kind stuck. But I can understand the pain on upgrading to 0.9.3

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by foobarbecue** [comment]
Yep, this decision makes sense now that I understand it. Happy 1.0 everyone!

**Pull request closed without merging**
