### PR TITLE
Documentation to cover use with CollectionFS

### PR DESCRIPTION
**Pull request by rhyslbw**
I've added a section to the docs explaining the need to change ownership if there are files being accessed external from the 'app' directory. This is to cover CFS, but covers generic use-cases

### CODE REVIEW

**Comment by arunoda** [comment]
Can you add this as a wiki: https://github.com/arunoda/meteor-up/wiki
and link that add the end of the readme under Additional Resources.

**Comment by rhyslbw** [comment]
Sure, that's a better place for it

**Comment by rhyslbw** [comment]
Ready to go

**Comment by arunoda** [comment]
Great.

**Pull request merged**
