### PR TITLE
Support deploying Meteor 0.9.0 bundles

### PR DESCRIPTION
**Pull request by Multiply**
I had problems deploy Meteor 0.9.0 release candidates, so in order to fix it, I changed the deploy scripts slightly.

This PR should also fix the need to specify Binary NPM Modules.

### CODE REVIEW

**Comment by arunoda** [comment]
Thanks. I just did a similar implementation, but with the support for older version of bundles as well.

**Comment by Multiply** [comment]
You removed complete support for pre-0.9.0. Consider adding binary npm modules back, if you want complete support

**Comment by arunoda** [comment]
Actually, we don't need binary npm modules support with 0.9
There is a way you publish binaries with your package to meteor server.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by Multiply** [comment]
Sorry I wasn't specific enough. It was for backwards compatibilty.

**Comment by arunoda** [comment]
Hmm. Seems fair enough.
I'll add it back.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Pull request closed without merging**
